sudo: required
dist: bionic

addons:
  apt:
    packages:
    - g++
    - cmake
    - libeigen3-dev
    - libglew-dev

before_install:
  - wget https://github.com/stevenlovegrove/Pangolin/archive/master.zip -O Pangolin.zip && unzip Pangolin.zip
  - mkdir -p Pangolin-master/build && cd Pangolin-master/build && cmake .. && make -j8 && sudo make install && cd ../..

language: cpp

compiler:
  - gcc

os:
  - linux

env:
  - BUILD_TYPE=Release

script:
  - mkdir build
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make -j8
